const stratagems = [
    {
        name: "Reinforce",
        sequence: ["up", "down", "right", "left", "up"],
        icon: "reinforce.svg",
        type: "mission",
    },
    {
        name: "Resupply",
        sequence: ["down", "down", "up", "right"],
        icon: "resupply.svg",
        type: "mission",
    },
    {
        name: "SOS Beacon",
        sequence: ["up", "down", "right", "up"],
        icon: "sos-beacon.svg",
        type: "mission",
    },
    {
        name: "SEAF Artillery",
        sequence: ["right", "up", "up", "down"],
        icon: "seaf-artillery.svg",
        type: "mission",
    },
    {
        name: "Hellbomb",
        sequence: ["down", "up", "left", "down", "up", "right", "down", "up"],
        icon: "hellbomb.svg",
        type: "mission",
    },
    {
        name: "Prospecting Drill",
        sequence: ["down", "down", "left", "right", "down", "down"],
        icon: "prospecting-drill.svg",
        type: "mission",
    },
    {
        name: "Super Earth Flag",
        sequence: ["down", "up", "down", "up"],
        icon: "super-earth-flag.svg",
        type: "mission",
    },
    {
        name: "Upload Data",
        sequence: ["left", "right", "up", "up", "up"],
        icon: "upload-data.svg",
        type: "mission",
    },
    {
        name: "Machine Gun",
        sequence: ["down", "left", "down", "up", "right"],
        icon: "machine-gun.svg",
        type: "supply:support-weapon",
    },
    {
        name: "Anti-Materiel Rifle",
        sequence: ["down", "left", "right", "up", "down"],
        icon: "anti-materiel-rifle.svg",
        type: "supply:support-weapon",
    },
    {
        name: "Stalwart",
        sequence: ["down", "left", "down", "up", "up", "left"],
        icon: "stalwart.svg",
        type: "supply:support-weapon",
    },
    {
        name: "Expendable Anti-Tank",
        sequence: ["down", "down", "left", "up", "right"],
        icon: "expendable-anti-tank.svg",
        type: "supply:support-weapon",
    },
    {
        name: "Recoilless Rifle",
        sequence: ["down", "left", "right", "right", "left"],
        icon: "recoilless-rifle.svg",
        type: "supply:support-weapon",
    },
    {
        name: "Flamethrower",
        sequence: ["down", "left", "up", "down", "up"],
        icon: "flamethrower.svg",
        type: "supply:support-weapon",
    },
    {
        name: "Autocannon",
        sequence: ["down", "left", "down", "up", "up", "right"],
        icon: "autocannon.svg",
        type: "supply:support-weapon",
    },
    {
        name: "Railgun",
        sequence: ["down", "right", "down", "up", "left", "right"],
        icon: "railgun.svg",
        type: "supply:support-weapon",
    },
    {
        name: "FAF-14 SPEAR Launcher",
        sequence: ["down", "down", "up", "down", "down"],
        icon: "faf-14-spear-launcher.svg",
        type: "supply:support-weapon",
    },
    {
        name: "Orbital Gatling Barrage",
        sequence: ["right", "down", "left", "up", "up"],
        icon: "orbital-gatling-barrage.svg",
        type: "offensive:orbital",
    },
    {
        name: "Orbital Airburst Strike",
        sequence: ["right", "right", "right"],
        icon: "orbital-airburst-strike.svg",
        type: "offensive:orbital",
    },
    {
        name: "Orbital 120MM HE Barrage",
        sequence: ["right", "right", "down", "left", "right", "down"],
        icon: "orbital-120mm-he-barrage.svg",
        type: "offensive:orbital",
    },
    {
        name: "Orbital 380MM HE Barrage",
        sequence: ["right", "down", "up", "up", "left", "down", "down"],
        icon: "orbital-380mm-he-barrage.svg",
        type: "offensive:orbital",
    },
    {
        name: "Orbital Walking Barrage",
        sequence: ["right", "down", "right", "down", "right", "down"],
        icon: "orbital-walking-barrage.svg",
        type: "offensive:orbital",
    },
    {
        name: "Orbital Laser",
        sequence: ["right", "down", "up", "right", "down"],
        icon: "orbital-laser.svg",
        type: "offensive:orbital",
    },
    {
        name: "Orbital Railcannon Strike",
        sequence: ["right", "up", "down", "down", "right"],
        icon: "orbital-railcannon-strike.svg",
        type: "offensive:orbital",
    },
    {
        name: "Eagle Strafing Run",
        sequence: ["up", "right", "right"],
        icon: "eagle-strafing-run.svg",
        type: "offensive:eagle",
    },
    {
        name: "Eagle Airstrike",
        sequence: ["up", "right", "down", "right"],
        icon: "eagle-airstrike.svg",
        type: "offensive:eagle",
    },
    {
        name: "Eagle Cluster Bomb",
        sequence: ["up", "right", "down", "down", "right"],
        icon: "eagle-cluster-bomb.svg",
        type: "offensive:eagle",
    },
    {
        name: "Eagle Napalm Airstrike",
        sequence: ["up", "right", "down", "up"],
        icon: "eagle-napalm-airstrike.svg",
        type: "offensive:eagle",
    },
    {
        name: "Jump Pack",
        sequence: ["down", "up", "up", "down", "up"],
        icon: "jump-pack.svg",
        type: "supply:backpack",
    },
    {
        name: "Eagle Smoke Strike",
        sequence: ["up", "right", "up", "down"],
        icon: "eagle-smoke-strike.svg",
        type: "offensive:eagle",
    },
    {
        name: "Eagle 110MM Rocket Pods",
        sequence: ["up", "right", "up", "left"],
        icon: "eagle-110mm-rocket-pods.svg",
        type: "offensive:eagle",
    },
    {
        name: "Eagle 500KG Bomb",
        sequence: ["up", "right", "down", "down", "down"],
        icon: "eagle-500kg-bomb.svg",
        type: "offensive:eagle",
    },
    {
        name: "Eagle Rearm",
        sequence: ["up", "up", "left", "up", "right"],
        icon: "eagle-rearm.svg",
        type: "offensive:eagle",
    },
    {
        name: "Orbital Precision Strike",
        sequence: ["right", "right", "up"],
        icon: "orbital-precision-strike.svg",
        type: "offensive:orbital",
    },
    {
        name: "Orbital Gas Strike",
        sequence: ["right", "right", "down", "right"],
        icon: "orbital-gas-strike.svg",
        type: "offensive:orbital",
    },
    {
        name: "Orbital EMS Strike",
        sequence: ["right", "right", "left", "down"],
        icon: "orbital-ems-strike.svg",
        type: "offensive:orbital",
    },
    {
        name: "Orbital Smoke Strike",
        sequence: ["right", "right", "down", "up"],
        icon: "orbital-smoke-strike.svg",
        type: "offensive:orbital",
    },
    {
        name: "HMG Emplacement",
        sequence: ["down", "up", "left", "right", "right", "left"],
        icon: "hmg-emplacement.svg",
        type: "defensive",
    },
    {
        name: "Shield Generator Pack",
        sequence: ["down", "up", "left", "right", "left", "right"],
        icon: "shield-generator-pack.svg",
        type: "supply:backpack",
    },
    {
        name: "A/ARC-3 Tesla Tower",
        sequence: ["down", "up", "right", "up", "left", "right"],
        icon: "a-arc-3-tesla-tower.svg",
        type: "defensive",
    },
    {
        name: "Anti-Personnel Minefield",
        sequence: ["down", "left", "up", "right"],
        icon: "anti-personnel-minefield.svg",
        type: "defensive",
    },
    {
        name: "Supply Pack",
        sequence: ["down", "left", "down", "up", "up", "down"],
        icon: "supply-pack.svg",
        type: "supply:backpack",
    },
    {
        name: "Grenade Launcher",
        sequence: ["down", "left", "up", "left", "down"],
        icon: "grenade-launcher.svg",
        type: "supply:support-weapon",
    },
    {
        name: "Laser Cannon",
        sequence: ["down", "left", "down", "up", "left"],
        icon: "laser-cannon.svg",
        type: "supply:support-weapon",
    },
    {
        name: "Incendiary Mines",
        sequence: ["down", "left", "left", "down"],
        icon: "incendiary-mines.svg",
        type: "defensive",
    },
    {
        name: "Guard Dog Rover",
        sequence: ["down", "up", "left", "up", "right", "right"],
        icon: "guard-dog-rover.svg",
        type: "supply:backpack",
    },
    {
        name: "Ballistic Shield Backpack",
        sequence: ["down", "left", "down", "down", "up", "left"],
        icon: "ballistic-shield-backpack.svg",
        type: "supply:backpack",
    },
    {
        name: "Arc Thrower",
        sequence: ["down", "right", "down", "up", "left", "left"],
        icon: "arc-thrower.svg",
        type: "supply:support-weapon",
    },
    {
        name: "Machine Gun Sentry",
        sequence: ["down", "up", "right", "right", "up"],
        icon: "machine-gun-sentry.svg",
        type: "defensive",
    },
    {
        name: "Gatling Sentry",
        sequence: ["down", "up", "right", "left"],
        icon: "gatling-sentry.svg",
        type: "defensive",
    },
    {
        name: "Mortar Sentry",
        sequence: ["down", "up", "right", "right", "down"],
        icon: "mortar-sentry.svg",
        type: "defensive",
    },
    {
        name: "Guard Dog",
        sequence: ["down", "up", "left", "up", "right", "down"],
        icon: "guard-dog.svg",
        type: "supply:backpack",
    },
    {
        name: "Autocannon Sentry",
        sequence: ["down", "up", "right", "up", "left", "up"],
        icon: "autocannon-sentry.svg",
        type: "defensive",
    },
    {
        name: "Rocket Sentry",
        sequence: ["down", "up", "right", "right", "left"],
        icon: "rocket-sentry.svg",
        type: "defensive",
    },
    {
        name: "EMS Mortar Sentry",
        sequence: ["down", "up", "right", "down", "right"],
        icon: "ems-mortar-sentry.svg",
        type: "defensive",
    },
    {
        name: "Patriot Exosuit",
        sequence: ["left", "down", "right", "up", "left", "down", "down"],
        icon: "patriot-exosuit.svg",
        type: "supply:vehicle",
    },
];
