const stratagems = [
    {
        name: "Reinforce",
        sequence: ["up", "down", "right", "left", "up"],
        icon: "reinforce.svg",
        type: "mission",
    },
    {
        name: "Resupply",
        sequence: ["down", "down", "up", "right"],
        icon: "resupply.svg",
        type: "mission",
    },
    {
        name: "SOS Beacon",
        sequence: ["up", "down", "right", "up"],
        icon: "sos_beacon.svg",
        type: "mission",
    },
    {
        name: "SEAF Artillery",
        sequence: ["right", "up", "up", "down"],
        icon: "seaf_artillery.svg",
        type: "mission",
    },
    {
        name: "Hellbomb",
        sequence: ["down", "up", "left", "down", "up", "right", "down", "up"],
        icon: "hellbomb.svg",
        type: "mission",
    },
    {
        name: "Prospecting Drill",
        sequence: ["down", "down", "left", "right", "down", "down"],
        icon: "prospecting_drill.svg",
        type: "mission",
    },
    {
        name: "Super Earth Flag",
        sequence: ["down", "up", "down", "up"],
        icon: "super_earth_flag.svg",
        type: "mission",
    },
    {
        name: "Upload Data",
        sequence: ["left", "right", "up", "up", "up"],
        icon: "upload_data.svg",
        type: "mission",
    },
    {
        name: "Machine Gun",
        sequence: ["down", "left", "down", "up", "right"],
        icon: "machine_gun.svg",
        type: "supply:support-weapon",
    },
    {
        name: "Anti-Materiel Rifle",
        sequence: ["down", "left", "right", "up", "down"],
        icon: "anti-materiel_rifle.svg",
        type: "supply:support-weapon",
    },
    {
        name: "Stalwart",
        sequence: ["down", "left", "down", "up", "up", "left"],
        icon: "stalwart.svg",
        type: "supply:support-weapon",
    },
    {
        name: "Expendable Anti-Tank",
        sequence: ["down", "down", "left", "up", "right"],
        icon: "expendable_anti-tank.svg",
        type: "supply:support-weapon",
    },
    {
        name: "Recoilless Rifle",
        sequence: ["down", "left", "right", "right", "left"],
        icon: "recoilless_rifle.svg",
        type: "supply:support-weapon",
    },
    {
        name: "Flamethrower",
        sequence: ["down", "left", "up", "down", "up"],
        icon: "flamethrower.svg",
        type: "supply:support-weapon",
    },
    {
        name: "Autocannon",
        sequence: ["down", "left", "down", "up", "up", "right"],
        icon: "autocannon.svg",
        type: "supply:support-weapon",
    },
    {
        name: "Railgun",
        sequence: ["down", "right", "down", "up", "left", "right"],
        icon: "railgun.svg",
        type: "supply:support-weapon",
    },
    {
        name: "FAF-14 SPEAR Launcher",
        sequence: ["down", "down", "up", "down", "down"],
        icon: "faf-14-spear-launcher.svg",
        type: "supply:support-weapon",
    },
    {
        name: "Orbital Gatling Barrage",
        sequence: ["right", "down", "left", "up", "up"],
        icon: "orbital_gatling_barrage.svg",
        type: "offensive:orbital",
    },
    {
        name: "Orbital Airburst Strike",
        sequence: ["right", "right", "right"],
        icon: "orbital_airburst_strike.svg",
        type: "offensive:orbital",
    },
    {
        name: "Orbital 120MM HE Barrage",
        sequence: ["right", "right", "down", "left", "right", "down"],
        icon: "orbital_120mm_he_barrage.svg",
        type: "offensive:orbital",
    },
    {
        name: "Orbital 380MM HE Barrage",
        sequence: ["right", "down", "up", "up", "left", "down", "down"],
        icon: "orbital_380mm_he_barrage.svg",
        type: "offensive:orbital",
    },
    {
        name: "Orbital Walking Barrage",
        sequence: ["right", "down", "right", "down", "right", "down"],
        icon: "orbital_walking_barrage.svg",
        type: "offensive:orbital",
    },
    {
        name: "Orbital Laser",
        sequence: ["right", "down", "up", "right", "down"],
        icon: "orbital_laser.svg",
        type: "offensive:orbital",
    },
    {
        name: "Orbital Railcannon Strike",
        sequence: ["right", "up", "down", "down", "right"],
        icon: "orbital_railcannon_strike.svg",
        type: "offensive:orbital",
    },
    {
        name: "Eagle Strafing Run",
        sequence: ["up", "right", "right"],
        icon: "eagle_strafing_run.svg",
        type: "offensive:eagle",
    },
    {
        name: "Eagle Airstrike",
        sequence: ["up", "right", "down", "right"],
        icon: "eagle_airstrike.svg",
        type: "offensive:eagle",
    },
    {
        name: "Eagle Cluster Bomb",
        sequence: ["up", "right", "down", "down", "right"],
        icon: "eagle_cluster_bomb.svg",
        type: "offensive:eagle",
    },
    {
        name: "Eagle Napalm Airstrike",
        sequence: ["up", "right", "down", "up"],
        icon: "eagle_napalm_airstrike.svg",
        type: "offensive:eagle",
    },
    {
        name: "Jump Pack",
        sequence: ["down", "up", "up", "down", "up"],
        icon: "jump_pack.svg",
        type: "supply:backpack",
    },
    {
        name: "Eagle Smoke Strike",
        sequence: ["up", "right", "up", "down"],
        icon: "eagle_smoke_strike.svg",
        type: "offensive:eagle",
    },
    {
        name: "Eagle 110MM Rocket Pods",
        sequence: ["up", "right", "up", "left"],
        icon: "eagle_110mm_rocket_pods.svg",
        type: "offensive:eagle",
    },
    {
        name: "Eagle 500KG Bomb",
        sequence: ["up", "right", "down", "down", "down"],
        icon: "eagle_500kg_bomb.svg",
        type: "offensive:eagle",
    },
    {
        name: "Eagle Rearm",
        sequence: ["up", "up", "left", "up", "right"],
        icon: "eagle_rearm.svg",
        type: "offensive:eagle",
    },
    {
        name: "Orbital Precision Strike",
        sequence: ["right", "right", "up"],
        icon: "orbital_precision_strike.svg",
        type: "offensive:orbital",
    },
    {
        name: "Orbital Gas Strike",
        sequence: ["right", "right", "down", "right"],
        icon: "orbital_gas_strike.svg",
        type: "offensive:orbital",
    },
    {
        name: "Orbital EMS Strike",
        sequence: ["right", "right", "left", "down"],
        icon: "orbital_ems_strike.svg",
        type: "offensive:orbital",
    },
    {
        name: "Orbital Smoke Strike",
        sequence: ["right", "right", "down", "up"],
        icon: "orbital_smoke_strike.svg",
        type: "offensive:orbital",
    },
    {
        name: "HMG Emplacement",
        sequence: ["down", "up", "left", "right", "right", "left"],
        icon: "hmg_emplacement.svg",
        type: "defensive",
    },
    {
        name: "Shield Generator Pack",
        sequence: ["down", "up", "left", "right", "left", "right"],
        icon: "shield_generator_pack.svg",
        type: "supply:backpack",
    },
    {
        name: "A/ARC-3 Tesla Tower",
        sequence: ["down", "up", "right", "up", "left", "right"],
        icon: "a-arc-3-tesla-tower.svg",
        type: "defensive",
    },
    {
        name: "Anti-Personnel Minefield",
        sequence: ["down", "left", "up", "right"],
        icon: "anti-personnel_minefield.svg",
        type: "defensive",
    },
    {
        name: "Supply Pack",
        sequence: ["down", "left", "down", "up", "up", "down"],
        icon: "supply_pack.svg",
        type: "supply:backpack",
    },
    {
        name: "Grenade Launcher",
        sequence: ["down", "left", "up", "left", "down"],
        icon: "grenade_launcher.svg",
        type: "supply:support-weapon",
    },
    {
        name: "Laser Cannon",
        sequence: ["down", "left", "down", "up", "left"],
        icon: "laser_cannon.svg",
        type: "supply:support-weapon",
    },
    {
        name: "Incendiary Mines",
        sequence: ["down", "left", "left", "down"],
        icon: "incendiary_mines.svg",
        type: "defensive",
    },
    {
        name: "Guard Dog Rover",
        sequence: ["down", "up", "left", "up", "right", "right"],
        icon: "guard_dog_rover.svg",
        type: "supply:backpack",
    },
    {
        name: "Ballistic Shield Backpack",
        sequence: ["down", "left", "down", "down", "up", "left"],
        icon: "ballistic_shield_backpack.svg",
        type: "supply:backpack",
    },
    {
        name: "Arc Thrower",
        sequence: ["down", "right", "down", "up", "left", "left"],
        icon: "arc_thrower.svg",
        type: "supply:support-weapon",
    },
    {
        name: "Machine Gun Sentry",
        sequence: ["down", "up", "right", "right", "up"],
        icon: "machine_gun_sentry.svg",
        type: "defensive",
    },
    {
        name: "Gatling Sentry",
        sequence: ["down", "up", "right", "left"],
        icon: "gatling_sentry.svg",
        type: "defensive",
    },
    {
        name: "Mortar Sentry",
        sequence: ["down", "up", "right", "right", "down"],
        icon: "mortar_sentry.svg",
        type: "defensive",
    },
    {
        name: "Guard Dog",
        sequence: ["down", "up", "left", "up", "right", "down"],
        icon: "guard_dog.svg",
        type: "supply:backpack",
    },
    {
        name: "Autocannon Sentry",
        sequence: ["down", "up", "right", "up", "left", "up"],
        icon: "autocannon_sentry.svg",
        type: "defensive",
    },
    {
        name: "Rocket Sentry",
        sequence: ["down", "up", "right", "right", "left"],
        icon: "rocket_sentry.svg",
        type: "defensive",
    },
    {
        name: "EMS Mortar Sentry",
        sequence: ["down", "up", "right", "down", "right"],
        icon: "ems_mortar_sentry.svg",
        type: "defensive",
    },
    {
        name: "Patriot Exosuit",
        sequence: ["left", "down", "right", "up", "left", "down", "down"],
        icon: "patriot_exosuit.svg",
        type: "supply:vehicle",
    },
];
